### ISSUE TITLE
Error occurs when trying to open settings

### ISSUE THREAD

**Issue by user7500** [aerobounce/Sublime-Pretty-Lua#1]
I've tried to ways to install this. One, add the repo to Package Control and install it from there. Two was the way listed on this repo. Both install methods result in an error when I try to open the settings menu. 
![image](https://user-images.githubusercontent.com/71734690/154853768-5daa93d7-1b0d-4a15-856e-8682a15e680e.png)
Also using the command, `Pretty Lua: Format` does nothing

**Comment by aerobounce** [comment]
In `Packages` directory (where you can open by Preferences > Browse Packages...), can you try:

```sh
git clone "https://github.com/aerobounce/Sublime-Pretty-Lua.git" "Pretty Lua"
```

**Comment by user7500** [comment]
It is now able to open the settings menu, but the format commands do not seem to work.
![image](https://user-images.githubusercontent.com/71734690/154854856-6e4b0307-f877-4021-95dc-38d33b6f0477.png)
After both running `Pretty Lua: Format` and saving the file while having `format_on_save` set to true
![image](https://user-images.githubusercontent.com/71734690/154854906-b1ee0daa-723d-467f-ba01-3466f22e2ab5.png)

**Comment by aerobounce** [comment]
Good.

Make sure you have installed `stylua`.
Now, on Linux / Windows, you have to specify absolute path to the `stylua` binary in settings.

**Comment by user7500** [comment]
It works! Thank you for your help
