### ISSUE TITLE
Instructions for manual installation: the instruction about path could use a clarification

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [aerobounce/Sublime-Pretty-Lua#2]
Does your step 4 mean to be about (1) enabling Sublime to find the executable or (2) enabling one's terminal/system to find that executable? [EDITED: I had written step _3_.]

One does need to do 1. One does it by editing the config file for the (manually installed) Sublime Package.

To do 2: well, if one has installed via Cargo, then, during that installation, Cargo itself provides instructions.

EDITED to fix a typo.

**Comment by aerobounce** [comment]
Step 3 which is "Clone this repository", is a way to manually install a Sublime Text Package. It has nothing to do with system nor shell, but the step is only for Sublime Text application to recognize Pretty Lua.

So, clone and then, in the packages' Settings,

```js
{
    // Binary path.
    "binary": "Absolute Path to stylua"
}
```

And you're ready to go.

**Comment by LinuxOnTheDesktop** [comment]
Sorry: I meant step _4_. I'll edit my first post (and mark it as edited).

**Comment by aerobounce** [comment]
Oh okay. Then, Step 4 means your (1):

> (1) enabling Sublime being to find the executable

On _Linux / Windows_ system, ST doesn't read your shell environment values. Which means, even if your `.bashrc` or `.zshrc` or whatever already have `PATH` to `stylua`, ST doesn't know it so you have to specify it in ST.

On _macOS_, ST reads shell's environment so it your shell is already set so you usually don't need do this. Thus, it's written as 'Linux / Windows users'.

Behavior of this is described in ST's Settings if you are interested.

**Comment by LinuxOnTheDesktop** [comment]
Thanks. Unfortunately, you miss my point. My point is this. Your instructions do not make it plain that step 4 has to do with a path for Sublime Text. That is: the reader of your instructions might think that step 4 is about changing the system path.

**Comment by aerobounce** [comment]
Ah! Okay.
Yes maybe true for some users, I've refined description. Thanks for pointing out.
